### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by moofMonkey**
- Implemented every, find, filter functions

 - Rewrote most code

 - Added reverse iteration optimization, new comment to disable it (FORWARD), and changed comment start to `loop-optimizer`:
loop-optimizer: KEEP
loop-optimizer: FORWARD

Also, some [benchmark](http://jsben.ch/qkwZM) - new iteration method will always be faster than old one.

### CODE REVIEW

**Comment by moofMonkey** [comment]
So, that PR would close #6.
Guys from #8, can you somehow confirm that `new Array()` will not conflict with any user code?

**Comment by moofMonkey** [comment]
@vihanb

**Comment by vihanb** [comment]
Thanks for the PR! These are large changes which is fine and they definitely to add plenty of useful features that this plugin could benefit from. I don't have the time to maintain this package unfortunately so in terms of this PR, if you'd be willing I could just hand you permission too the repository and the npm package so you could maintain it, or you could publish your own NPM package.

**Comment by moofMonkey** [comment]
Thanks for merging this PR! :)
I don’t know if I can maintain this repo well, because now I’m rarely visiting GitHub.
If you don't want to handle PRs (as I'll make at least 1 more PR if near future) - I'd like to get permission to this repo.

**Pull request merged**
